import { ClientProvider } from '@/core/providers/ClientProvider'
import type { Metadata } from 'next'

import '../styles/globals.scss'
import '@mantine/core/styles.css'

export const metadata: Metadata = {
    title: 'Lincode & Markha',
    description: 'Generated by LinCode',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body>
                <ClientProvider>{children}</ClientProvider>
            </body>
        </html>
    )
}
